preload = ~/.config/hypr/wallpaper.jpg
wallpaper = eDP-1,~/.config/hypr/wallpaper.jpg
wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/wallpaper.jpg
    fit_mode = cover
}

# Global fallback (just in case)
wallpaper {
    monitor = 
    path = ~/.config/hypr/wallpaper.jpg
    fit_mode = cover
}

splash = false
ipc = onwallpaper = HDMI-A-1,~/.config/hypr/wallpaper.jpg
splash = false
